/* ═══════════════════════════════════════════
   BLOG PAGE — JSON fetch + filter + pagination
   Data source: data/blog-posts.json
   Generated by: .github/workflows/fetch-blog.yml (6h cron)
   ═══════════════════════════════════════════ */

(function () {
  'use strict';

  const DATA_URL = 'data/blog-posts.json';
  const PAGE_SIZE = 9;
  const BLOG_URL = 'https://blog.naver.com/wyyezbrmztora';
  const FALLBACK_IMG = 'img/logo-hd.png'; // lightweight fallback

  const gridEl = document.getElementById('blogGrid');
  const filterEl = document.getElementById('blogFilter');
  const pagiEl = document.getElementById('blogPagination');
  const statusEl = document.getElementById('blogStatus');

  if (!gridEl) return;

  let state = {
    posts: [],
    categories: ['전체'],
    currentCat: '전체',
    currentPage: 1
  };

  // ── Utilities ───────────────────────────────────────────
  function formatDate(iso) {
    const d = new Date(iso);
    if (isNaN(d)) return '';
    const yyyy = d.getFullYear();
    const mm = String(d.getMonth() + 1).padStart(2, '0');
    const dd = String(d.getDate()).padStart(2, '0');
    return `${yyyy}.${mm}.${dd}`;
  }

  function truncate(s, n) {
    if (!s) return '';
    s = s.replace(/\s+/g, ' ').trim();
    return s.length > n ? s.slice(0, n - 1) + '…' : s;
  }

  function escapeHtml(s) {
    return String(s || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  // ── Rendering ───────────────────────────────────────────
  function renderFilter() {
    // Keep existing "전체" button, append others
    const existing = filterEl.querySelector('[data-cat="전체"]');
    filterEl.innerHTML = '';
    if (existing) filterEl.appendChild(existing);

    state.categories.forEach(cat => {
      if (cat === '전체') return;
      const btn = document.createElement('button');
      btn.className = 'blog-filter-btn';
      btn.dataset.cat = cat;
      btn.setAttribute('role', 'tab');
      btn.setAttribute('aria-selected', 'false');
      btn.textContent = cat;
      filterEl.appendChild(btn);
    });

    filterEl.addEventListener('click', onFilterClick);
  }

  function onFilterClick(e) {
    const btn = e.target.closest('.blog-filter-btn');
    if (!btn) return;
    const cat = btn.dataset.cat;
    if (cat === state.currentCat) return;

    filterEl.querySelectorAll('.blog-filter-btn').forEach(b => {
      const active = b.dataset.cat === cat;
      b.classList.toggle('is-active', active);
      b.setAttribute('aria-selected', active ? 'true' : 'false');
    });
    state.currentCat = cat;
    state.currentPage = 1;
    renderPage();
    window.scrollTo({ top: gridEl.offsetTop - 120, behavior: 'smooth' });
  }

  function filteredPosts() {
    return state.currentCat === '전체'
      ? state.posts
      : state.posts.filter(p => (p.category || '기타') === state.currentCat);
  }

  function renderPage() {
    const all = filteredPosts();
    const totalPages = Math.max(1, Math.ceil(all.length / PAGE_SIZE));
    state.currentPage = Math.min(state.currentPage, totalPages);

    const start = (state.currentPage - 1) * PAGE_SIZE;
    const items = all.slice(start, start + PAGE_SIZE);

    if (items.length === 0) {
      gridEl.innerHTML = `<p class="blog-empty" style="grid-column:1/-1;">해당 카테고리의 글이 아직 없습니다. <a href="${BLOG_URL}" target="_blank" rel="noopener">네이버 블로그에서 더 보기</a></p>`;
      pagiEl.innerHTML = '';
      return;
    }

    gridEl.innerHTML = items.map(renderCard).join('');
    renderPagination(totalPages);
  }

  function renderCard(p) {
    const safeTitle = escapeHtml(p.title || '(제목 없음)');
    const safeSummary = escapeHtml(truncate(p.summary, 110));
    const safeCat = escapeHtml(p.category || '기타');
    const date = formatDate(p.pubDate);
    const thumb = p.thumbnail
      ? `<img src="${escapeHtml(p.thumbnail)}" alt="" loading="lazy" referrerpolicy="no-referrer" onerror="this.parentElement.classList.add('is-placeholder');this.remove();this.parentElement.innerHTML='YONSEI'">`
      : '';

    return `
      <a class="blog-card" href="${escapeHtml(p.link)}" target="_blank" rel="noopener">
        <div class="blog-card-thumb ${thumb ? '' : 'is-placeholder'}">${thumb || 'YONSEI'}</div>
        <div class="blog-card-body">
          <div class="blog-card-meta">
            <span class="blog-card-cat">${safeCat}</span>
            <span class="blog-card-date">${date}</span>
          </div>
          <h3 class="blog-card-title">${safeTitle}</h3>
          <p class="blog-card-summary">${safeSummary}</p>
        </div>
      </a>
    `;
  }

  function renderPagination(totalPages) {
    if (totalPages <= 1) {
      pagiEl.innerHTML = '';
      return;
    }

    const cur = state.currentPage;
    const parts = [];

    // Previous
    parts.push(
      `<button type="button" ${cur === 1 ? 'class="is-disabled" aria-disabled="true"' : 'data-page="' + (cur - 1) + '"'} aria-label="이전">‹</button>`
    );

    // Page numbers with ellipsis
    const visible = new Set();
    visible.add(1);
    visible.add(totalPages);
    for (let i = cur - 1; i <= cur + 1; i++) {
      if (i > 1 && i < totalPages) visible.add(i);
    }
    visible.add(cur);

    const pages = Array.from(visible).sort((a, b) => a - b);
    let prev = 0;
    pages.forEach(n => {
      if (n - prev > 1) parts.push('<span class="ellipsis">…</span>');
      parts.push(
        n === cur
          ? `<button type="button" class="is-current" aria-current="page">${n}</button>`
          : `<button type="button" data-page="${n}">${n}</button>`
      );
      prev = n;
    });

    // Next
    parts.push(
      `<button type="button" ${cur === totalPages ? 'class="is-disabled" aria-disabled="true"' : 'data-page="' + (cur + 1) + '"'} aria-label="다음">›</button>`
    );

    pagiEl.innerHTML = parts.join('');
    pagiEl.addEventListener('click', onPaginationClick, { once: true });
  }

  function onPaginationClick(e) {
    const btn = e.target.closest('[data-page]');
    if (!btn) {
      // Re-bind for next render (since {once:true})
      return;
    }
    const n = parseInt(btn.dataset.page, 10);
    if (isNaN(n) || n === state.currentPage) return;
    state.currentPage = n;
    renderPage();
    window.scrollTo({ top: gridEl.offsetTop - 120, behavior: 'smooth' });
  }

  // ── Data loading ────────────────────────────────────────
  function setStatus(msg) {
    statusEl.textContent = msg || '';
  }

  async function loadData() {
    setStatus('불러오는 중…');
    try {
      const res = await fetch(DATA_URL, { cache: 'no-store' });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      const json = await res.json();
      state.posts = Array.isArray(json.posts) ? json.posts : [];
      state.categories = Array.isArray(json.categories) && json.categories.length > 0
        ? ['전체', ...json.categories.filter(c => c !== '전체')]
        : ['전체'];

      if (state.posts.length === 0) {
        setStatus('블로그 글을 불러오지 못했습니다. 네이버 블로그에서 직접 확인해주세요.');
        return;
      }

      renderFilter();
      renderPage();
      setStatus('');
    } catch (err) {
      console.warn('[blog.js] load failed:', err);
      setStatus('블로그 글을 불러오지 못했습니다. 네이버 블로그에서 직접 확인해주세요.');
      // Render minimal fallback card linking to Naver blog
      gridEl.innerHTML = `
        <a class="blog-card" href="${BLOG_URL}" target="_blank" rel="noopener" style="grid-column:1/-1;max-width:520px;margin:0 auto;">
          <div class="blog-card-thumb is-placeholder">NAVER BLOG</div>
          <div class="blog-card-body">
            <div class="blog-card-meta"><span class="blog-card-cat">네이버 블로그</span></div>
            <h3 class="blog-card-title">연세타이밍치과 네이버 블로그 바로가기</h3>
            <p class="blog-card-summary">최신 임상 케이스와 치과 건강 정보는 네이버 블로그에서 확인하세요.</p>
          </div>
        </a>
      `;
    }
  }

  // Kick off
  loadData();

  // Re-bind pagination click delegation (since once:true used above)
  pagiEl.addEventListener('click', function (e) {
    const btn = e.target.closest('[data-page]');
    if (!btn) return;
    const n = parseInt(btn.dataset.page, 10);
    if (isNaN(n) || n === state.currentPage) return;
    state.currentPage = n;
    renderPage();
    window.scrollTo({ top: gridEl.offsetTop - 120, behavior: 'smooth' });
  });
})();
